# Generated by Django 4.2.28 on 2026-02-21 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.JSONField(help_text='List of symptom codes or descriptions')),
                ('notes', models.TextField(blank=True)),
                ('urgency', models.CharField(choices=[('LOW', 'Low (Home care)'), ('MEDIUM', 'Medium (Clinic)'), ('HIGH', 'High (Emergency)')], max_length=10)),
                ('score', models.PositiveSmallIntegerField(default=0, help_text='Numeric urgency score 0-100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
