# Generated by Django 4.2.28 on 2026-02-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagesubmission',
            name='ai_summary',
            field=models.TextField(blank=True, default='', help_text='AI-generated summary for doctors'),
        ),
        migrations.AddField(
            model_name='triagesubmission',
            name='clinical_terminology',
            field=models.TextField(blank=True, default='', help_text='Medical terminology for symptoms'),
        ),
        migrations.AddField(
            model_name='triagesubmission',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='triagesubmission',
            name='patient_age',
            field=models.PositiveSmallIntegerField(default=0, help_text='Patient age'),
        ),
        migrations.AddField(
            model_name='triagesubmission',
            name='patient_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='triagesubmission',
            name='patient_name',
            field=models.CharField(default='Unknown', help_text='Patient full name', max_length=200),
        ),
        migrations.AddField(
            model_name='triagesubmission',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='triagesubmission',
            name='suggested_department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
